//---------------------------------------------------------------------------
//
// SCSI Target Emulator PiSCSI
// for Raspberry Pi
//
// Copyright (C) 2021-2023 Uwe Seimet
//
//---------------------------------------------------------------------------

//
// Each piscsi message sent to the piscsi server is preceded by the magic string "RASCSI".
// A message starts with a little endian 32 bit header which contains the protobuf message size.
// Unless explicitly specified the order of repeated data returned is undefined.
// All operations accept an optional access token, specified by the "token" parameter.
// All operations also accept an optional locale, specified with the "locale" parameter. If there is
// a localized error message piscsi returns it, with English being the fallback language.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: piscsi_interface.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The available device types
type PbDeviceType int32

const (
	PbDeviceType_UNDEFINED PbDeviceType = 0
	// Non-removable SASI drive, not supported anymore but must not be removed because of backwards compatibility
	//
	// Deprecated: Marked as deprecated in piscsi_interface.proto.
	PbDeviceType_SAHD PbDeviceType = 1
	// Non-removable SCSI drive
	PbDeviceType_SCHD PbDeviceType = 2
	// Removable SCSI drive
	PbDeviceType_SCRM PbDeviceType = 3
	// Magnoto-Optical drive
	PbDeviceType_SCMO PbDeviceType = 4
	// CD-ROM drive
	PbDeviceType_SCCD PbDeviceType = 5
	// Support for X68000 host bridge removed
	//
	// Deprecated: Marked as deprecated in piscsi_interface.proto.
	PbDeviceType_SCBR PbDeviceType = 6
	// DaynaPort network adapter
	PbDeviceType_SCDP PbDeviceType = 7
	// Host services device
	PbDeviceType_SCHS PbDeviceType = 8
	// Printer device
	PbDeviceType_SCLP PbDeviceType = 9
	// Streamer (tape) device
	PbDeviceType_SCTP PbDeviceType = 10
)

// Enum value maps for PbDeviceType.
var (
	PbDeviceType_name = map[int32]string{
		0:  "UNDEFINED",
		1:  "SAHD",
		2:  "SCHD",
		3:  "SCRM",
		4:  "SCMO",
		5:  "SCCD",
		6:  "SCBR",
		7:  "SCDP",
		8:  "SCHS",
		9:  "SCLP",
		10: "SCTP",
	}
	PbDeviceType_value = map[string]int32{
		"UNDEFINED": 0,
		"SAHD":      1,
		"SCHD":      2,
		"SCRM":      3,
		"SCMO":      4,
		"SCCD":      5,
		"SCBR":      6,
		"SCDP":      7,
		"SCHS":      8,
		"SCLP":      9,
		"SCTP":      10,
	}
)

func (x PbDeviceType) Enum() *PbDeviceType {
	p := new(PbDeviceType)
	*p = x
	return p
}

func (x PbDeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PbDeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_piscsi_interface_proto_enumTypes[0].Descriptor()
}

func (PbDeviceType) Type() protoreflect.EnumType {
	return &file_piscsi_interface_proto_enumTypes[0]
}

func (x PbDeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PbDeviceType.Descriptor instead.
func (PbDeviceType) EnumDescriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{0}
}

// piscsi remote operations, returning PbResult
type PbOperation int32

const (
	PbOperation_NO_OPERATION PbOperation = 0
	// Attach devices and return the new device list (PbDevicesInfo)
	// Parameters (depending on the device type):
	//
	//	"file": The filename relative to the default image folder
	//	"interface": A prioritized comma-separated list of interfaces to create a network bridge for
	//	"inet": The IP address and netmask for the network bridge
	//	"cmd": The command to be used for printing, with "%f" as file placeholder
	PbOperation_ATTACH PbOperation = 1
	// Detach a device and return the new device list (PbDevicesInfo)
	// Detaches all LUNs of that device which are equal to or higher than the LUN specified.
	PbOperation_DETACH PbOperation = 2
	// Detach all devices, does not require a device list
	PbOperation_DETACH_ALL PbOperation = 3
	// Start device
	PbOperation_START PbOperation = 4
	// Stop device, e.g. park drive
	PbOperation_STOP PbOperation = 5
	// Insert medium
	// Parameters:
	//
	//	"file": The filename, relative to the default image folder
	PbOperation_INSERT PbOperation = 6
	// Eject medium
	PbOperation_EJECT PbOperation = 7
	// Write-protect medium (not possible for read-only media)
	PbOperation_PROTECT PbOperation = 8
	// Make medium writable (not possible for read-only media)
	PbOperation_UNPROTECT PbOperation = 9
	// Gets the server information (PbServerInfo). Calling this operation without a list of operations should
	// be avoided because this may return a lot of data. More specific other operations should be used instead.
	// Parameters:
	//
	//	"operations": Optional case insensitive comma-separated list of operation names to return data for,
	//	e.g. "version_info,log_level_info". Unknown operation names are ignored. If this parameter is missing
	//	the full set of data supported by PbServerInfo is returned.
	//	"folder_pattern": Optional filter, only folder names containing the case-insensitive pattern are returned
	//	"file_pattern": Optional filter, only filenames containing the case-insensitive pattern are returned
	PbOperation_SERVER_INFO PbOperation = 10
	// Get piscsi server version (PbVersionInfo)
	PbOperation_VERSION_INFO PbOperation = 11
	// Get information on attached devices (PbDevicesInfo)
	// Returns data for all attached devices if the device list is empty.
	PbOperation_DEVICES_INFO PbOperation = 12
	// Get device properties by device type (PbDeviceTypesInfo)
	PbOperation_DEVICE_TYPES_INFO PbOperation = 13
	// Get information on available image files in the default image folder (PbImageFilesInfo)
	// Parameters:
	//
	//	"folder_pattern": Optional filter, only folder names containing the case-insensitive pattern are returned
	//	"file_pattern": Optional filter, only filenames containing the case-insensitive pattern are returned
	PbOperation_DEFAULT_IMAGE_FILES_INFO PbOperation = 14
	// Get information on an image file (not necessarily in the default image folder).
	// Parameters:
	//
	//	"file": The filename. Either an absolute path or a path relative to the default image folder.
	PbOperation_IMAGE_FILE_INFO PbOperation = 15
	// Get information on the available log levels and the current log level (PbLogLevelInfo)
	PbOperation_LOG_LEVEL_INFO PbOperation = 16
	// Get the names of the available network interfaces (PbNetworkInterfacesInfo)
	// Only lists interfaces that are up.
	PbOperation_NETWORK_INTERFACES_INFO PbOperation = 17
	// Get the mapping of extensions to device types (PbMappingInfo)
	PbOperation_MAPPING_INFO PbOperation = 18
	// Get the list of reserved device IDs (PbReservedIdsInfo)
	PbOperation_RESERVED_IDS_INFO PbOperation = 19
	// Set the default folder for image files. This folder must be located in /home.
	// Parameters:
	//
	//	"folder": The path of the default folder, relative to the user's home folder if relative.
	PbOperation_DEFAULT_FOLDER PbOperation = 20
	// Set the log level.
	// Parameters:
	//
	//	"level": The new log level
	PbOperation_LOG_LEVEL PbOperation = 21
	// Block IDs from being used, usually the IDs of the initiators (computers) in the SCSI chain.
	// Parameters:
	//
	//	"ids": A comma-separated list of IDs to reserve, or an empty string in order not to reserve any ID.
	PbOperation_RESERVE_IDS PbOperation = 22
	// Shut down the piscsi process or shut down/reboot the Pi
	// Parameters:
	//
	//	"mode": The shutdown mode, one of
	//	  "rascsi": Shuts down the piscsi process ("rascsi" instead of "piscsi" for backwards compatibility)
	//	  "system": Shuts down the Pi
	//	  "reboot": Reboots the Pi
	PbOperation_SHUT_DOWN PbOperation = 23
	// Create an image file. The image file must not yet exist.
	// Parameters:
	//
	//	"file": The filename, relative to the default image folder
	//	"size": The file size in bytes, must be a multiple of 512
	//	"read_only": Optional, "true" (case-insensitive) in order to create a read-only file
	PbOperation_CREATE_IMAGE PbOperation = 24
	// Delete an image file.
	// Parameters:
	//
	//	"file": The filename, relative to the default image folder.
	PbOperation_DELETE_IMAGE PbOperation = 25
	// Rename/Move an image file.
	// Parameters:
	//
	//	"from": The old filename, relative to the default image folder
	//	"to": The new filename, relative to the default image folder
	//
	// The new filename must not yet exist.
	PbOperation_RENAME_IMAGE PbOperation = 26
	// Copy an image file.
	// Parameters:
	//
	//	"from": The source filename, relative to the default image folder
	//	"to": The destination filename, relative to the default image folder
	//	"read_only": Optional, "true" (case-insensitive) in order to create a read-only file
	//
	// The destination filename must not yet exist.
	PbOperation_COPY_IMAGE PbOperation = 27
	// Write-protect an image file.
	// Parameters:
	//
	//	"file": The filename, relative to the default image folder
	PbOperation_PROTECT_IMAGE PbOperation = 28
	// Make an image file writable.
	// Parameters:
	//
	//	"file": The filename, relative to the default image folder
	PbOperation_UNPROTECT_IMAGE PbOperation = 29
	// Check whether an authentication token is valid. A client can use this operation in order to
	// find out whether piscsi authentication is enable or to use piscsi authentication for securing
	// client-internal operations.
	PbOperation_CHECK_AUTHENTICATION PbOperation = 30
	// Get operation meta data (PbOperationInfo)
	PbOperation_OPERATION_INFO PbOperation = 31
	// Get statistics (PbStatisticsInfo)
	PbOperation_STATISTICS_INFO PbOperation = 32
)

// Enum value maps for PbOperation.
var (
	PbOperation_name = map[int32]string{
		0:  "NO_OPERATION",
		1:  "ATTACH",
		2:  "DETACH",
		3:  "DETACH_ALL",
		4:  "START",
		5:  "STOP",
		6:  "INSERT",
		7:  "EJECT",
		8:  "PROTECT",
		9:  "UNPROTECT",
		10: "SERVER_INFO",
		11: "VERSION_INFO",
		12: "DEVICES_INFO",
		13: "DEVICE_TYPES_INFO",
		14: "DEFAULT_IMAGE_FILES_INFO",
		15: "IMAGE_FILE_INFO",
		16: "LOG_LEVEL_INFO",
		17: "NETWORK_INTERFACES_INFO",
		18: "MAPPING_INFO",
		19: "RESERVED_IDS_INFO",
		20: "DEFAULT_FOLDER",
		21: "LOG_LEVEL",
		22: "RESERVE_IDS",
		23: "SHUT_DOWN",
		24: "CREATE_IMAGE",
		25: "DELETE_IMAGE",
		26: "RENAME_IMAGE",
		27: "COPY_IMAGE",
		28: "PROTECT_IMAGE",
		29: "UNPROTECT_IMAGE",
		30: "CHECK_AUTHENTICATION",
		31: "OPERATION_INFO",
		32: "STATISTICS_INFO",
	}
	PbOperation_value = map[string]int32{
		"NO_OPERATION":             0,
		"ATTACH":                   1,
		"DETACH":                   2,
		"DETACH_ALL":               3,
		"START":                    4,
		"STOP":                     5,
		"INSERT":                   6,
		"EJECT":                    7,
		"PROTECT":                  8,
		"UNPROTECT":                9,
		"SERVER_INFO":              10,
		"VERSION_INFO":             11,
		"DEVICES_INFO":             12,
		"DEVICE_TYPES_INFO":        13,
		"DEFAULT_IMAGE_FILES_INFO": 14,
		"IMAGE_FILE_INFO":          15,
		"LOG_LEVEL_INFO":           16,
		"NETWORK_INTERFACES_INFO":  17,
		"MAPPING_INFO":             18,
		"RESERVED_IDS_INFO":        19,
		"DEFAULT_FOLDER":           20,
		"LOG_LEVEL":                21,
		"RESERVE_IDS":              22,
		"SHUT_DOWN":                23,
		"CREATE_IMAGE":             24,
		"DELETE_IMAGE":             25,
		"RENAME_IMAGE":             26,
		"COPY_IMAGE":               27,
		"PROTECT_IMAGE":            28,
		"UNPROTECT_IMAGE":          29,
		"CHECK_AUTHENTICATION":     30,
		"OPERATION_INFO":           31,
		"STATISTICS_INFO":          32,
	}
)

func (x PbOperation) Enum() *PbOperation {
	p := new(PbOperation)
	*p = x
	return p
}

func (x PbOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PbOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_piscsi_interface_proto_enumTypes[1].Descriptor()
}

func (PbOperation) Type() protoreflect.EnumType {
	return &file_piscsi_interface_proto_enumTypes[1]
}

func (x PbOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PbOperation.Descriptor instead.
func (PbOperation) EnumDescriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{1}
}

// piscsi special purpose error codes for cases where a textual error message may not be not sufficient.
// The client may react on this code, e.g. by prompting the user for an authentication token.
type PbErrorCode int32

const (
	// No error code available
	PbErrorCode_NO_ERROR_CODE PbErrorCode = 0
	// The client sent an operation code not supported by this server
	PbErrorCode_UNKNOWN_OPERATION PbErrorCode = 1
	// Authentication/Authorization error
	PbErrorCode_UNAUTHORIZED PbErrorCode = 2
)

// Enum value maps for PbErrorCode.
var (
	PbErrorCode_name = map[int32]string{
		0: "NO_ERROR_CODE",
		1: "UNKNOWN_OPERATION",
		2: "UNAUTHORIZED",
	}
	PbErrorCode_value = map[string]int32{
		"NO_ERROR_CODE":     0,
		"UNKNOWN_OPERATION": 1,
		"UNAUTHORIZED":      2,
	}
)

func (x PbErrorCode) Enum() *PbErrorCode {
	p := new(PbErrorCode)
	*p = x
	return p
}

func (x PbErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PbErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_piscsi_interface_proto_enumTypes[2].Descriptor()
}

func (PbErrorCode) Type() protoreflect.EnumType {
	return &file_piscsi_interface_proto_enumTypes[2]
}

func (x PbErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PbErrorCode.Descriptor instead.
func (PbErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{2}
}

// Statistics categories ordered by increasing severity
type PbStatisticsCategory int32

const (
	PbStatisticsCategory_CATEGORY_NONE    PbStatisticsCategory = 0
	PbStatisticsCategory_CATEGORY_INFO    PbStatisticsCategory = 1
	PbStatisticsCategory_CATEGORY_WARNING PbStatisticsCategory = 2
	PbStatisticsCategory_CATEGORY_ERROR   PbStatisticsCategory = 3
)

// Enum value maps for PbStatisticsCategory.
var (
	PbStatisticsCategory_name = map[int32]string{
		0: "CATEGORY_NONE",
		1: "CATEGORY_INFO",
		2: "CATEGORY_WARNING",
		3: "CATEGORY_ERROR",
	}
	PbStatisticsCategory_value = map[string]int32{
		"CATEGORY_NONE":    0,
		"CATEGORY_INFO":    1,
		"CATEGORY_WARNING": 2,
		"CATEGORY_ERROR":   3,
	}
)

func (x PbStatisticsCategory) Enum() *PbStatisticsCategory {
	p := new(PbStatisticsCategory)
	*p = x
	return p
}

func (x PbStatisticsCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PbStatisticsCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_piscsi_interface_proto_enumTypes[3].Descriptor()
}

func (PbStatisticsCategory) Type() protoreflect.EnumType {
	return &file_piscsi_interface_proto_enumTypes[3]
}

func (x PbStatisticsCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PbStatisticsCategory.Descriptor instead.
func (PbStatisticsCategory) EnumDescriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{3}
}

// The operation parameter meta data. The parameter data type is provided by the protobuf API.
type PbOperationParameter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional short description
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// There is no specific set of permitted values if empty
	PermittedValues []string `protobuf:"bytes,3,rep,name=permitted_values,json=permittedValues,proto3" json:"permitted_values,omitempty"`
	// Optional default value
	DefaultValue string `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	// True if this parameter is mandatory
	IsMandatory   bool `protobuf:"varint,5,opt,name=is_mandatory,json=isMandatory,proto3" json:"is_mandatory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbOperationParameter) Reset() {
	*x = PbOperationParameter{}
	mi := &file_piscsi_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbOperationParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbOperationParameter) ProtoMessage() {}

func (x *PbOperationParameter) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbOperationParameter.ProtoReflect.Descriptor instead.
func (*PbOperationParameter) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{0}
}

func (x *PbOperationParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PbOperationParameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PbOperationParameter) GetPermittedValues() []string {
	if x != nil {
		return x.PermittedValues
	}
	return nil
}

func (x *PbOperationParameter) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *PbOperationParameter) GetIsMandatory() bool {
	if x != nil {
		return x.IsMandatory
	}
	return false
}

// The list of parameters supported by an operation
type PbOperationMetaData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The operation name at the time the server-side protobuf code was generated.
	ServerSideName string `protobuf:"bytes,1,opt,name=server_side_name,json=serverSideName,proto3" json:"server_side_name,omitempty"`
	// Optional short description
	Description   string                  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    []*PbOperationParameter `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbOperationMetaData) Reset() {
	*x = PbOperationMetaData{}
	mi := &file_piscsi_interface_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbOperationMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbOperationMetaData) ProtoMessage() {}

func (x *PbOperationMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbOperationMetaData.ProtoReflect.Descriptor instead.
func (*PbOperationMetaData) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{1}
}

func (x *PbOperationMetaData) GetServerSideName() string {
	if x != nil {
		return x.ServerSideName
	}
	return ""
}

func (x *PbOperationMetaData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PbOperationMetaData) GetParameters() []*PbOperationParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// Mapping of operations to their ordinals
type PbOperationInfo struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Operations    map[int32]*PbOperationMetaData `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbOperationInfo) Reset() {
	*x = PbOperationInfo{}
	mi := &file_piscsi_interface_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbOperationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbOperationInfo) ProtoMessage() {}

func (x *PbOperationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbOperationInfo.ProtoReflect.Descriptor instead.
func (*PbOperationInfo) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{2}
}

func (x *PbOperationInfo) GetOperations() map[int32]*PbOperationMetaData {
	if x != nil {
		return x.Operations
	}
	return nil
}

// The supported file extensions mapped to their respective device types
type PbMappingInfo struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Mapping       map[string]PbDeviceType `protobuf:"bytes,1,rep,name=mapping,proto3" json:"mapping,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=piscsi_interface.PbDeviceType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbMappingInfo) Reset() {
	*x = PbMappingInfo{}
	mi := &file_piscsi_interface_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbMappingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbMappingInfo) ProtoMessage() {}

func (x *PbMappingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbMappingInfo.ProtoReflect.Descriptor instead.
func (*PbMappingInfo) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{3}
}

func (x *PbMappingInfo) GetMapping() map[string]PbDeviceType {
	if x != nil {
		return x.Mapping
	}
	return nil
}

// The properties supported by a device
type PbDeviceProperties struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Read-only media (e.g. CD-ROMs) are not protectable but permanently read-only
	ReadOnly bool `protobuf:"varint,1,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	// Medium can be write-protected
	Protectable bool `protobuf:"varint,2,opt,name=protectable,proto3" json:"protectable,omitempty"`
	// Device can be stopped, e.g. parked
	Stoppable bool `protobuf:"varint,3,opt,name=stoppable,proto3" json:"stoppable,omitempty"`
	// Medium can be removed
	Removable bool `protobuf:"varint,4,opt,name=removable,proto3" json:"removable,omitempty"`
	// Medium can be locked
	Lockable bool `protobuf:"varint,5,opt,name=lockable,proto3" json:"lockable,omitempty"`
	// Device supports image file as a parameter
	SupportsFile bool `protobuf:"varint,6,opt,name=supports_file,json=supportsFile,proto3" json:"supports_file,omitempty"`
	// Device supports parameters other than a filename
	SupportsParams bool `protobuf:"varint,7,opt,name=supports_params,json=supportsParams,proto3" json:"supports_params,omitempty"`
	// List of default parameters, if any (requires supports_params to be true)
	DefaultParams map[string]string `protobuf:"bytes,8,rep,name=default_params,json=defaultParams,proto3" json:"default_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// LUN numbers this device can have, usually 32
	Luns int32 `protobuf:"varint,9,opt,name=luns,proto3" json:"luns,omitempty"`
	// Unordered list of permitted block sizes in bytes, empty if the block size is not configurable
	BlockSizes    []uint32 `protobuf:"varint,10,rep,packed,name=block_sizes,json=blockSizes,proto3" json:"block_sizes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbDeviceProperties) Reset() {
	*x = PbDeviceProperties{}
	mi := &file_piscsi_interface_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbDeviceProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbDeviceProperties) ProtoMessage() {}

func (x *PbDeviceProperties) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbDeviceProperties.ProtoReflect.Descriptor instead.
func (*PbDeviceProperties) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{4}
}

func (x *PbDeviceProperties) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *PbDeviceProperties) GetProtectable() bool {
	if x != nil {
		return x.Protectable
	}
	return false
}

func (x *PbDeviceProperties) GetStoppable() bool {
	if x != nil {
		return x.Stoppable
	}
	return false
}

func (x *PbDeviceProperties) GetRemovable() bool {
	if x != nil {
		return x.Removable
	}
	return false
}

func (x *PbDeviceProperties) GetLockable() bool {
	if x != nil {
		return x.Lockable
	}
	return false
}

func (x *PbDeviceProperties) GetSupportsFile() bool {
	if x != nil {
		return x.SupportsFile
	}
	return false
}

func (x *PbDeviceProperties) GetSupportsParams() bool {
	if x != nil {
		return x.SupportsParams
	}
	return false
}

func (x *PbDeviceProperties) GetDefaultParams() map[string]string {
	if x != nil {
		return x.DefaultParams
	}
	return nil
}

func (x *PbDeviceProperties) GetLuns() int32 {
	if x != nil {
		return x.Luns
	}
	return 0
}

func (x *PbDeviceProperties) GetBlockSizes() []uint32 {
	if x != nil {
		return x.BlockSizes
	}
	return nil
}

// The status of a device, only meaningful if the respective feature is supported
type PbDeviceStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Medium is write-protected
	Protected bool `protobuf:"varint,1,opt,name=protected,proto3" json:"protected,omitempty"`
	// Device is stopped, e.g. parked
	Stopped bool `protobuf:"varint,2,opt,name=stopped,proto3" json:"stopped,omitempty"`
	// Medium is removed
	Removed bool `protobuf:"varint,3,opt,name=removed,proto3" json:"removed,omitempty"`
	// Medium is locked
	Locked        bool `protobuf:"varint,4,opt,name=locked,proto3" json:"locked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbDeviceStatus) Reset() {
	*x = PbDeviceStatus{}
	mi := &file_piscsi_interface_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbDeviceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbDeviceStatus) ProtoMessage() {}

func (x *PbDeviceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbDeviceStatus.ProtoReflect.Descriptor instead.
func (*PbDeviceStatus) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{5}
}

func (x *PbDeviceStatus) GetProtected() bool {
	if x != nil {
		return x.Protected
	}
	return false
}

func (x *PbDeviceStatus) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

func (x *PbDeviceStatus) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

func (x *PbDeviceStatus) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

// Device properties by device type. (Note that a protobuf map cannot be used because enums cannot be map keys.)
type PbDeviceTypeProperties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PbDeviceType           `protobuf:"varint,1,opt,name=type,proto3,enum=piscsi_interface.PbDeviceType" json:"type,omitempty"`
	Properties    *PbDeviceProperties    `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbDeviceTypeProperties) Reset() {
	*x = PbDeviceTypeProperties{}
	mi := &file_piscsi_interface_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbDeviceTypeProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbDeviceTypeProperties) ProtoMessage() {}

func (x *PbDeviceTypeProperties) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbDeviceTypeProperties.ProtoReflect.Descriptor instead.
func (*PbDeviceTypeProperties) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{6}
}

func (x *PbDeviceTypeProperties) GetType() PbDeviceType {
	if x != nil {
		return x.Type
	}
	return PbDeviceType_UNDEFINED
}

func (x *PbDeviceTypeProperties) GetProperties() *PbDeviceProperties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type PbDeviceTypesInfo struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Properties    []*PbDeviceTypeProperties `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbDeviceTypesInfo) Reset() {
	*x = PbDeviceTypesInfo{}
	mi := &file_piscsi_interface_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbDeviceTypesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbDeviceTypesInfo) ProtoMessage() {}

func (x *PbDeviceTypesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbDeviceTypesInfo.ProtoReflect.Descriptor instead.
func (*PbDeviceTypesInfo) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{7}
}

func (x *PbDeviceTypesInfo) GetProperties() []*PbDeviceTypeProperties {
	if x != nil {
		return x.Properties
	}
	return nil
}

// The image file data
type PbImageFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The assumed device type, based on the filename extension
	Type PbDeviceType `protobuf:"varint,2,opt,name=type,proto3,enum=piscsi_interface.PbDeviceType" json:"type,omitempty"`
	// The file size in bytes, 0 for block devices in /dev
	Size          uint64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ReadOnly      bool   `protobuf:"varint,4,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbImageFile) Reset() {
	*x = PbImageFile{}
	mi := &file_piscsi_interface_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbImageFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbImageFile) ProtoMessage() {}

func (x *PbImageFile) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbImageFile.ProtoReflect.Descriptor instead.
func (*PbImageFile) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{8}
}

func (x *PbImageFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PbImageFile) GetType() PbDeviceType {
	if x != nil {
		return x.Type
	}
	return PbDeviceType_UNDEFINED
}

func (x *PbImageFile) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PbImageFile) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

// The default image folder and the image files it contains
type PbImageFilesInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DefaultImageFolder string                 `protobuf:"bytes,1,opt,name=default_image_folder,json=defaultImageFolder,proto3" json:"default_image_folder,omitempty"`
	ImageFiles         []*PbImageFile         `protobuf:"bytes,2,rep,name=image_files,json=imageFiles,proto3" json:"image_files,omitempty"`
	// The maximum nesting depth, configured with the -R option
	Depth         int32 `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbImageFilesInfo) Reset() {
	*x = PbImageFilesInfo{}
	mi := &file_piscsi_interface_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbImageFilesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbImageFilesInfo) ProtoMessage() {}

func (x *PbImageFilesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbImageFilesInfo.ProtoReflect.Descriptor instead.
func (*PbImageFilesInfo) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{9}
}

func (x *PbImageFilesInfo) GetDefaultImageFolder() string {
	if x != nil {
		return x.DefaultImageFolder
	}
	return ""
}

func (x *PbImageFilesInfo) GetImageFiles() []*PbImageFile {
	if x != nil {
		return x.ImageFiles
	}
	return nil
}

func (x *PbImageFilesInfo) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// Log level information
type PbLogLevelInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of available log levels, ordered by increasing by severity
	LogLevels       []string `protobuf:"bytes,2,rep,name=log_levels,json=logLevels,proto3" json:"log_levels,omitempty"`
	CurrentLogLevel string   `protobuf:"bytes,3,opt,name=current_log_level,json=currentLogLevel,proto3" json:"current_log_level,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PbLogLevelInfo) Reset() {
	*x = PbLogLevelInfo{}
	mi := &file_piscsi_interface_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbLogLevelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbLogLevelInfo) ProtoMessage() {}

func (x *PbLogLevelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbLogLevelInfo.ProtoReflect.Descriptor instead.
func (*PbLogLevelInfo) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{10}
}

func (x *PbLogLevelInfo) GetLogLevels() []string {
	if x != nil {
		return x.LogLevels
	}
	return nil
}

func (x *PbLogLevelInfo) GetCurrentLogLevel() string {
	if x != nil {
		return x.CurrentLogLevel
	}
	return ""
}

// The network interfaces information
type PbNetworkInterfacesInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          []string               `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbNetworkInterfacesInfo) Reset() {
	*x = PbNetworkInterfacesInfo{}
	mi := &file_piscsi_interface_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbNetworkInterfacesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbNetworkInterfacesInfo) ProtoMessage() {}

func (x *PbNetworkInterfacesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbNetworkInterfacesInfo.ProtoReflect.Descriptor instead.
func (*PbNetworkInterfacesInfo) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{11}
}

func (x *PbNetworkInterfacesInfo) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

type PbStatistics struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Category PbStatisticsCategory   `protobuf:"varint,1,opt,name=category,proto3,enum=piscsi_interface.PbStatisticsCategory" json:"category,omitempty"`
	// The device ID and LUN for this statistics item. Both are -1 if the item is not device specific.
	Id   int32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Unit int32 `protobuf:"varint,3,opt,name=unit,proto3" json:"unit,omitempty"`
	// A symbolic unique item name, may be used for I18N. Supported values and their categories:
	//
	//	"read_error_count" (ERROR, SCHD/SCRM/SCMO/SCCD)
	//	"write_error_count" (ERROR, SCHD/SCRM/SCMO)
	//	"cache_miss_read_count" (INFO, SCHD/SCRM/SCMO/SCCD)
	//	"cache_miss_write_count" (INFO, SCHD/SCRM/SCMO)
	//	"sector_read_count" (INFO, SCHD/SCRM/SCMO/SCCD)
	//	"sector_write_count" (INFO, SCHD/SCRM/SCMO)
	//	"byte_read_count" (INFO, SCDP)
	//	"byte_write_count" (INFO, SCDP)
	//	"print_error_count" (ERROR, SCLP)
	//	"print_warning_count" (WARNING, SCLP)
	//	"file_print_count" (INFO, SCLP)
	//	"byte_receive_count" (INFO, SCLP)
	Key           string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Value         uint64 `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbStatistics) Reset() {
	*x = PbStatistics{}
	mi := &file_piscsi_interface_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbStatistics) ProtoMessage() {}

func (x *PbStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbStatistics.ProtoReflect.Descriptor instead.
func (*PbStatistics) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{12}
}

func (x *PbStatistics) GetCategory() PbStatisticsCategory {
	if x != nil {
		return x.Category
	}
	return PbStatisticsCategory_CATEGORY_NONE
}

func (x *PbStatistics) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PbStatistics) GetUnit() int32 {
	if x != nil {
		return x.Unit
	}
	return 0
}

func (x *PbStatistics) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PbStatistics) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// The information on collected statistics
type PbStatisticsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statistics    []*PbStatistics        `protobuf:"bytes,1,rep,name=statistics,proto3" json:"statistics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbStatisticsInfo) Reset() {
	*x = PbStatisticsInfo{}
	mi := &file_piscsi_interface_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbStatisticsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbStatisticsInfo) ProtoMessage() {}

func (x *PbStatisticsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbStatisticsInfo.ProtoReflect.Descriptor instead.
func (*PbStatisticsInfo) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{13}
}

func (x *PbStatisticsInfo) GetStatistics() []*PbStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

// The device definition, sent from the client to the server
type PbDeviceDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Unit  int32                  `protobuf:"varint,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Type  PbDeviceType           `protobuf:"varint,3,opt,name=type,proto3,enum=piscsi_interface.PbDeviceType" json:"type,omitempty"`
	// Device specific named parameters, e.g. the name of an image file
	Params map[string]string `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The optional block size in bytes per sector, must be one of the supported block sizes
	BlockSize int32 `protobuf:"varint,5,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	// The device name components
	Vendor   string `protobuf:"bytes,6,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Product  string `protobuf:"bytes,7,opt,name=product,proto3" json:"product,omitempty"`
	Revision string `protobuf:"bytes,8,opt,name=revision,proto3" json:"revision,omitempty"`
	// Create a write-protected device
	Protected     bool `protobuf:"varint,9,opt,name=protected,proto3" json:"protected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbDeviceDefinition) Reset() {
	*x = PbDeviceDefinition{}
	mi := &file_piscsi_interface_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbDeviceDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbDeviceDefinition) ProtoMessage() {}

func (x *PbDeviceDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbDeviceDefinition.ProtoReflect.Descriptor instead.
func (*PbDeviceDefinition) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{14}
}

func (x *PbDeviceDefinition) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PbDeviceDefinition) GetUnit() int32 {
	if x != nil {
		return x.Unit
	}
	return 0
}

func (x *PbDeviceDefinition) GetType() PbDeviceType {
	if x != nil {
		return x.Type
	}
	return PbDeviceType_UNDEFINED
}

func (x *PbDeviceDefinition) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *PbDeviceDefinition) GetBlockSize() int32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *PbDeviceDefinition) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *PbDeviceDefinition) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *PbDeviceDefinition) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *PbDeviceDefinition) GetProtected() bool {
	if x != nil {
		return x.Protected
	}
	return false
}

// The device data, sent from the server to the client
type PbDevice struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Unit       int32                  `protobuf:"varint,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Type       PbDeviceType           `protobuf:"varint,3,opt,name=type,proto3,enum=piscsi_interface.PbDeviceType" json:"type,omitempty"`
	Properties *PbDeviceProperties    `protobuf:"bytes,4,opt,name=properties,proto3" json:"properties,omitempty"`
	Status     *PbDeviceStatus        `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// Image file information, if the device supports image files
	File *PbImageFile `protobuf:"bytes,6,opt,name=file,proto3" json:"file,omitempty"`
	// Effective parameters the device was created with
	Params   map[string]string `protobuf:"bytes,7,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Vendor   string            `protobuf:"bytes,8,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Product  string            `protobuf:"bytes,9,opt,name=product,proto3" json:"product,omitempty"`
	Revision string            `protobuf:"bytes,10,opt,name=revision,proto3" json:"revision,omitempty"`
	// Block size in bytes
	BlockSize int32 `protobuf:"varint,11,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	// Number of blocks
	BlockCount    uint64 `protobuf:"varint,12,opt,name=block_count,json=blockCount,proto3" json:"block_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbDevice) Reset() {
	*x = PbDevice{}
	mi := &file_piscsi_interface_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbDevice) ProtoMessage() {}

func (x *PbDevice) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbDevice.ProtoReflect.Descriptor instead.
func (*PbDevice) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{15}
}

func (x *PbDevice) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PbDevice) GetUnit() int32 {
	if x != nil {
		return x.Unit
	}
	return 0
}

func (x *PbDevice) GetType() PbDeviceType {
	if x != nil {
		return x.Type
	}
	return PbDeviceType_UNDEFINED
}

func (x *PbDevice) GetProperties() *PbDeviceProperties {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *PbDevice) GetStatus() *PbDeviceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *PbDevice) GetFile() *PbImageFile {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *PbDevice) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *PbDevice) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *PbDevice) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *PbDevice) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *PbDevice) GetBlockSize() int32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *PbDevice) GetBlockCount() uint64 {
	if x != nil {
		return x.BlockCount
	}
	return 0
}

type PbDevicesInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*PbDevice            `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbDevicesInfo) Reset() {
	*x = PbDevicesInfo{}
	mi := &file_piscsi_interface_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbDevicesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbDevicesInfo) ProtoMessage() {}

func (x *PbDevicesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbDevicesInfo.ProtoReflect.Descriptor instead.
func (*PbDevicesInfo) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{16}
}

func (x *PbDevicesInfo) GetDevices() []*PbDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

// The reserved device IDs
type PbReservedIdsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int32                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbReservedIdsInfo) Reset() {
	*x = PbReservedIdsInfo{}
	mi := &file_piscsi_interface_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbReservedIdsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbReservedIdsInfo) ProtoMessage() {}

func (x *PbReservedIdsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbReservedIdsInfo.ProtoReflect.Descriptor instead.
func (*PbReservedIdsInfo) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{17}
}

func (x *PbReservedIdsInfo) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

// Piscsi server version information
type PbVersionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The piscsi version
	MajorVersion int32 `protobuf:"varint,1,opt,name=major_version,json=majorVersion,proto3" json:"major_version,omitempty"`
	MinorVersion int32 `protobuf:"varint,2,opt,name=minor_version,json=minorVersion,proto3" json:"minor_version,omitempty"`
	// < 0 for a development version, = 0 if there is no patch yet
	PatchVersion  int32 `protobuf:"varint,3,opt,name=patch_version,json=patchVersion,proto3" json:"patch_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbVersionInfo) Reset() {
	*x = PbVersionInfo{}
	mi := &file_piscsi_interface_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbVersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbVersionInfo) ProtoMessage() {}

func (x *PbVersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbVersionInfo.ProtoReflect.Descriptor instead.
func (*PbVersionInfo) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{18}
}

func (x *PbVersionInfo) GetMajorVersion() int32 {
	if x != nil {
		return x.MajorVersion
	}
	return 0
}

func (x *PbVersionInfo) GetMinorVersion() int32 {
	if x != nil {
		return x.MinorVersion
	}
	return 0
}

func (x *PbVersionInfo) GetPatchVersion() int32 {
	if x != nil {
		return x.PatchVersion
	}
	return 0
}

// Commands piscsi can execute and their parameters
type PbCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Operation PbOperation            `protobuf:"varint,1,opt,name=operation,proto3,enum=piscsi_interface.PbOperation" json:"operation,omitempty"`
	// The non-empty list of devices for this command
	Devices []*PbDeviceDefinition `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	// The named parameters for the operation, e.g. a filename, or a network interface list
	Params        map[string]string `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbCommand) Reset() {
	*x = PbCommand{}
	mi := &file_piscsi_interface_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbCommand) ProtoMessage() {}

func (x *PbCommand) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbCommand.ProtoReflect.Descriptor instead.
func (*PbCommand) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{19}
}

func (x *PbCommand) GetOperation() PbOperation {
	if x != nil {
		return x.Operation
	}
	return PbOperation_NO_OPERATION
}

func (x *PbCommand) GetDevices() []*PbDeviceDefinition {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *PbCommand) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// The result of a command
type PbResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// false means that an error occurred
	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// An optional error or information message, depending on the status. A string without trailing CR/LF.
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// An optional error code. Only to be used in cases where textual information is not sufficient.
	ErrorCode PbErrorCode `protobuf:"varint,14,opt,name=error_code,json=errorCode,proto3,enum=piscsi_interface.PbErrorCode" json:"error_code,omitempty"`
	// Optional additional result data
	//
	// Types that are valid to be assigned to Result:
	//
	//	*PbResult_ServerInfo
	//	*PbResult_VersionInfo
	//	*PbResult_LogLevelInfo
	//	*PbResult_DevicesInfo
	//	*PbResult_DeviceTypesInfo
	//	*PbResult_ImageFilesInfo
	//	*PbResult_ImageFileInfo
	//	*PbResult_NetworkInterfacesInfo
	//	*PbResult_MappingInfo
	//	*PbResult_ReservedIdsInfo
	//	*PbResult_OperationInfo
	//	*PbResult_StatisticsInfo
	Result        isPbResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbResult) Reset() {
	*x = PbResult{}
	mi := &file_piscsi_interface_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbResult) ProtoMessage() {}

func (x *PbResult) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbResult.ProtoReflect.Descriptor instead.
func (*PbResult) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{20}
}

func (x *PbResult) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *PbResult) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PbResult) GetErrorCode() PbErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return PbErrorCode_NO_ERROR_CODE
}

func (x *PbResult) GetResult() isPbResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *PbResult) GetServerInfo() *PbServerInfo {
	if x != nil {
		if x, ok := x.Result.(*PbResult_ServerInfo); ok {
			return x.ServerInfo
		}
	}
	return nil
}

func (x *PbResult) GetVersionInfo() *PbVersionInfo {
	if x != nil {
		if x, ok := x.Result.(*PbResult_VersionInfo); ok {
			return x.VersionInfo
		}
	}
	return nil
}

func (x *PbResult) GetLogLevelInfo() *PbLogLevelInfo {
	if x != nil {
		if x, ok := x.Result.(*PbResult_LogLevelInfo); ok {
			return x.LogLevelInfo
		}
	}
	return nil
}

func (x *PbResult) GetDevicesInfo() *PbDevicesInfo {
	if x != nil {
		if x, ok := x.Result.(*PbResult_DevicesInfo); ok {
			return x.DevicesInfo
		}
	}
	return nil
}

func (x *PbResult) GetDeviceTypesInfo() *PbDeviceTypesInfo {
	if x != nil {
		if x, ok := x.Result.(*PbResult_DeviceTypesInfo); ok {
			return x.DeviceTypesInfo
		}
	}
	return nil
}

func (x *PbResult) GetImageFilesInfo() *PbImageFilesInfo {
	if x != nil {
		if x, ok := x.Result.(*PbResult_ImageFilesInfo); ok {
			return x.ImageFilesInfo
		}
	}
	return nil
}

func (x *PbResult) GetImageFileInfo() *PbImageFile {
	if x != nil {
		if x, ok := x.Result.(*PbResult_ImageFileInfo); ok {
			return x.ImageFileInfo
		}
	}
	return nil
}

func (x *PbResult) GetNetworkInterfacesInfo() *PbNetworkInterfacesInfo {
	if x != nil {
		if x, ok := x.Result.(*PbResult_NetworkInterfacesInfo); ok {
			return x.NetworkInterfacesInfo
		}
	}
	return nil
}

func (x *PbResult) GetMappingInfo() *PbMappingInfo {
	if x != nil {
		if x, ok := x.Result.(*PbResult_MappingInfo); ok {
			return x.MappingInfo
		}
	}
	return nil
}

func (x *PbResult) GetReservedIdsInfo() *PbReservedIdsInfo {
	if x != nil {
		if x, ok := x.Result.(*PbResult_ReservedIdsInfo); ok {
			return x.ReservedIdsInfo
		}
	}
	return nil
}

func (x *PbResult) GetOperationInfo() *PbOperationInfo {
	if x != nil {
		if x, ok := x.Result.(*PbResult_OperationInfo); ok {
			return x.OperationInfo
		}
	}
	return nil
}

func (x *PbResult) GetStatisticsInfo() *PbStatisticsInfo {
	if x != nil {
		if x, ok := x.Result.(*PbResult_StatisticsInfo); ok {
			return x.StatisticsInfo
		}
	}
	return nil
}

type isPbResult_Result interface {
	isPbResult_Result()
}

type PbResult_ServerInfo struct {
	// The result of a SERVER_INFO command
	ServerInfo *PbServerInfo `protobuf:"bytes,3,opt,name=server_info,json=serverInfo,proto3,oneof"`
}

type PbResult_VersionInfo struct {
	// The result of a VERSION_INFO command
	VersionInfo *PbVersionInfo `protobuf:"bytes,4,opt,name=version_info,json=versionInfo,proto3,oneof"`
}

type PbResult_LogLevelInfo struct {
	// The result of a LOG_LEVEL_INFO command
	LogLevelInfo *PbLogLevelInfo `protobuf:"bytes,5,opt,name=log_level_info,json=logLevelInfo,proto3,oneof"`
}

type PbResult_DevicesInfo struct {
	// The result of a DEVICES_INFO, ATTACH or DETACH command
	DevicesInfo *PbDevicesInfo `protobuf:"bytes,6,opt,name=devices_info,json=devicesInfo,proto3,oneof"`
}

type PbResult_DeviceTypesInfo struct {
	// The result of a DEVICE_TYPES_INFO command
	DeviceTypesInfo *PbDeviceTypesInfo `protobuf:"bytes,7,opt,name=device_types_info,json=deviceTypesInfo,proto3,oneof"`
}

type PbResult_ImageFilesInfo struct {
	// The result of a DEFAULT_IMAGE_FILES_INFO command
	ImageFilesInfo *PbImageFilesInfo `protobuf:"bytes,8,opt,name=image_files_info,json=imageFilesInfo,proto3,oneof"`
}

type PbResult_ImageFileInfo struct {
	// The result of an IMAGE_FILE_INFO command
	ImageFileInfo *PbImageFile `protobuf:"bytes,9,opt,name=image_file_info,json=imageFileInfo,proto3,oneof"`
}

type PbResult_NetworkInterfacesInfo struct {
	// The result of a NETWORK_INTERFACES_INFO command
	NetworkInterfacesInfo *PbNetworkInterfacesInfo `protobuf:"bytes,10,opt,name=network_interfaces_info,json=networkInterfacesInfo,proto3,oneof"`
}

type PbResult_MappingInfo struct {
	// The result of an MAPPING_INFO command
	MappingInfo *PbMappingInfo `protobuf:"bytes,11,opt,name=mapping_info,json=mappingInfo,proto3,oneof"`
}

type PbResult_ReservedIdsInfo struct {
	// The result of a RESERVED_IDS_INFO command
	ReservedIdsInfo *PbReservedIdsInfo `protobuf:"bytes,12,opt,name=reserved_ids_info,json=reservedIdsInfo,proto3,oneof"`
}

type PbResult_OperationInfo struct {
	// The result of an OPERATION_INFO command
	OperationInfo *PbOperationInfo `protobuf:"bytes,13,opt,name=operation_info,json=operationInfo,proto3,oneof"`
}

type PbResult_StatisticsInfo struct {
	// The result of a STATISTICS_INFO command
	StatisticsInfo *PbStatisticsInfo `protobuf:"bytes,15,opt,name=statistics_info,json=statisticsInfo,proto3,oneof"`
}

func (*PbResult_ServerInfo) isPbResult_Result() {}

func (*PbResult_VersionInfo) isPbResult_Result() {}

func (*PbResult_LogLevelInfo) isPbResult_Result() {}

func (*PbResult_DevicesInfo) isPbResult_Result() {}

func (*PbResult_DeviceTypesInfo) isPbResult_Result() {}

func (*PbResult_ImageFilesInfo) isPbResult_Result() {}

func (*PbResult_ImageFileInfo) isPbResult_Result() {}

func (*PbResult_NetworkInterfacesInfo) isPbResult_Result() {}

func (*PbResult_MappingInfo) isPbResult_Result() {}

func (*PbResult_ReservedIdsInfo) isPbResult_Result() {}

func (*PbResult_OperationInfo) isPbResult_Result() {}

func (*PbResult_StatisticsInfo) isPbResult_Result() {}

// The piscsi server information. All data can also be requested with individual commands.
type PbServerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The piscsi server version data
	VersionInfo *PbVersionInfo `protobuf:"bytes,1,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	// The available log levels and the current log level
	LogLevelInfo *PbLogLevelInfo `protobuf:"bytes,2,opt,name=log_level_info,json=logLevelInfo,proto3" json:"log_level_info,omitempty"`
	// Supported device types and their properties
	DeviceTypesInfo *PbDeviceTypesInfo `protobuf:"bytes,3,opt,name=device_types_info,json=deviceTypesInfo,proto3" json:"device_types_info,omitempty"`
	// The image files in the default folder
	ImageFilesInfo *PbImageFilesInfo `protobuf:"bytes,4,opt,name=image_files_info,json=imageFilesInfo,proto3" json:"image_files_info,omitempty"`
	// The available (up) network interfaces
	NetworkInterfacesInfo *PbNetworkInterfacesInfo `protobuf:"bytes,5,opt,name=network_interfaces_info,json=networkInterfacesInfo,proto3" json:"network_interfaces_info,omitempty"`
	// The extensions to device types mapping
	MappingInfo *PbMappingInfo `protobuf:"bytes,6,opt,name=mapping_info,json=mappingInfo,proto3" json:"mapping_info,omitempty"`
	// The reserved device IDs
	ReservedIdsInfo *PbReservedIdsInfo `protobuf:"bytes,7,opt,name=reserved_ids_info,json=reservedIdsInfo,proto3" json:"reserved_ids_info,omitempty"`
	// The attached devices
	DevicesInfo *PbDevicesInfo `protobuf:"bytes,8,opt,name=devices_info,json=devicesInfo,proto3" json:"devices_info,omitempty"`
	// The operation meta data
	OperationInfo *PbOperationInfo `protobuf:"bytes,9,opt,name=operation_info,json=operationInfo,proto3" json:"operation_info,omitempty"`
	// The statistics
	StatisticsInfo *PbStatisticsInfo `protobuf:"bytes,10,opt,name=statistics_info,json=statisticsInfo,proto3" json:"statistics_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PbServerInfo) Reset() {
	*x = PbServerInfo{}
	mi := &file_piscsi_interface_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbServerInfo) ProtoMessage() {}

func (x *PbServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_piscsi_interface_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbServerInfo.ProtoReflect.Descriptor instead.
func (*PbServerInfo) Descriptor() ([]byte, []int) {
	return file_piscsi_interface_proto_rawDescGZIP(), []int{21}
}

func (x *PbServerInfo) GetVersionInfo() *PbVersionInfo {
	if x != nil {
		return x.VersionInfo
	}
	return nil
}

func (x *PbServerInfo) GetLogLevelInfo() *PbLogLevelInfo {
	if x != nil {
		return x.LogLevelInfo
	}
	return nil
}

func (x *PbServerInfo) GetDeviceTypesInfo() *PbDeviceTypesInfo {
	if x != nil {
		return x.DeviceTypesInfo
	}
	return nil
}

func (x *PbServerInfo) GetImageFilesInfo() *PbImageFilesInfo {
	if x != nil {
		return x.ImageFilesInfo
	}
	return nil
}

func (x *PbServerInfo) GetNetworkInterfacesInfo() *PbNetworkInterfacesInfo {
	if x != nil {
		return x.NetworkInterfacesInfo
	}
	return nil
}

func (x *PbServerInfo) GetMappingInfo() *PbMappingInfo {
	if x != nil {
		return x.MappingInfo
	}
	return nil
}

func (x *PbServerInfo) GetReservedIdsInfo() *PbReservedIdsInfo {
	if x != nil {
		return x.ReservedIdsInfo
	}
	return nil
}

func (x *PbServerInfo) GetDevicesInfo() *PbDevicesInfo {
	if x != nil {
		return x.DevicesInfo
	}
	return nil
}

func (x *PbServerInfo) GetOperationInfo() *PbOperationInfo {
	if x != nil {
		return x.OperationInfo
	}
	return nil
}

func (x *PbServerInfo) GetStatisticsInfo() *PbStatisticsInfo {
	if x != nil {
		return x.StatisticsInfo
	}
	return nil
}

var File_piscsi_interface_proto protoreflect.FileDescriptor

const file_piscsi_interface_proto_rawDesc = "" +
	"\n" +
	"\x16piscsi_interface.proto\x12\x10piscsi_interface\"\xbf\x01\n" +
	"\x14PbOperationParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12)\n" +
	"\x10permitted_values\x18\x03 \x03(\tR\x0fpermittedValues\x12#\n" +
	"\rdefault_value\x18\x04 \x01(\tR\fdefaultValue\x12!\n" +
	"\fis_mandatory\x18\x05 \x01(\bR\visMandatory\"\xa9\x01\n" +
	"\x13PbOperationMetaData\x12(\n" +
	"\x10server_side_name\x18\x01 \x01(\tR\x0eserverSideName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12F\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2&.piscsi_interface.PbOperationParameterR\n" +
	"parameters\"\xca\x01\n" +
	"\x0fPbOperationInfo\x12Q\n" +
	"\n" +
	"operations\x18\x01 \x03(\v21.piscsi_interface.PbOperationInfo.OperationsEntryR\n" +
	"operations\x1ad\n" +
	"\x0fOperationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.piscsi_interface.PbOperationMetaDataR\x05value:\x028\x01\"\xb3\x01\n" +
	"\rPbMappingInfo\x12F\n" +
	"\amapping\x18\x01 \x03(\v2,.piscsi_interface.PbMappingInfo.MappingEntryR\amapping\x1aZ\n" +
	"\fMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\x0e2\x1e.piscsi_interface.PbDeviceTypeR\x05value:\x028\x01\"\xd0\x03\n" +
	"\x12PbDeviceProperties\x12\x1b\n" +
	"\tread_only\x18\x01 \x01(\bR\breadOnly\x12 \n" +
	"\vprotectable\x18\x02 \x01(\bR\vprotectable\x12\x1c\n" +
	"\tstoppable\x18\x03 \x01(\bR\tstoppable\x12\x1c\n" +
	"\tremovable\x18\x04 \x01(\bR\tremovable\x12\x1a\n" +
	"\blockable\x18\x05 \x01(\bR\blockable\x12#\n" +
	"\rsupports_file\x18\x06 \x01(\bR\fsupportsFile\x12'\n" +
	"\x0fsupports_params\x18\a \x01(\bR\x0esupportsParams\x12^\n" +
	"\x0edefault_params\x18\b \x03(\v27.piscsi_interface.PbDeviceProperties.DefaultParamsEntryR\rdefaultParams\x12\x12\n" +
	"\x04luns\x18\t \x01(\x05R\x04luns\x12\x1f\n" +
	"\vblock_sizes\x18\n" +
	" \x03(\rR\n" +
	"blockSizes\x1a@\n" +
	"\x12DefaultParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"z\n" +
	"\x0ePbDeviceStatus\x12\x1c\n" +
	"\tprotected\x18\x01 \x01(\bR\tprotected\x12\x18\n" +
	"\astopped\x18\x02 \x01(\bR\astopped\x12\x18\n" +
	"\aremoved\x18\x03 \x01(\bR\aremoved\x12\x16\n" +
	"\x06locked\x18\x04 \x01(\bR\x06locked\"\x92\x01\n" +
	"\x16PbDeviceTypeProperties\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.piscsi_interface.PbDeviceTypeR\x04type\x12D\n" +
	"\n" +
	"properties\x18\x02 \x01(\v2$.piscsi_interface.PbDevicePropertiesR\n" +
	"properties\"]\n" +
	"\x11PbDeviceTypesInfo\x12H\n" +
	"\n" +
	"properties\x18\x01 \x03(\v2(.piscsi_interface.PbDeviceTypePropertiesR\n" +
	"properties\"\x86\x01\n" +
	"\vPbImageFile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1e.piscsi_interface.PbDeviceTypeR\x04type\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x1b\n" +
	"\tread_only\x18\x04 \x01(\bR\breadOnly\"\x9a\x01\n" +
	"\x10PbImageFilesInfo\x120\n" +
	"\x14default_image_folder\x18\x01 \x01(\tR\x12defaultImageFolder\x12>\n" +
	"\vimage_files\x18\x02 \x03(\v2\x1d.piscsi_interface.PbImageFileR\n" +
	"imageFiles\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\x05R\x05depth\"[\n" +
	"\x0ePbLogLevelInfo\x12\x1d\n" +
	"\n" +
	"log_levels\x18\x02 \x03(\tR\tlogLevels\x12*\n" +
	"\x11current_log_level\x18\x03 \x01(\tR\x0fcurrentLogLevel\"-\n" +
	"\x17PbNetworkInterfacesInfo\x12\x12\n" +
	"\x04name\x18\x01 \x03(\tR\x04name\"\x9e\x01\n" +
	"\fPbStatistics\x12B\n" +
	"\bcategory\x18\x01 \x01(\x0e2&.piscsi_interface.PbStatisticsCategoryR\bcategory\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\x05R\x04unit\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x04R\x05value\"R\n" +
	"\x10PbStatisticsInfo\x12>\n" +
	"\n" +
	"statistics\x18\x01 \x03(\v2\x1e.piscsi_interface.PbStatisticsR\n" +
	"statistics\"\xfc\x02\n" +
	"\x12PbDeviceDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\x05R\x04unit\x122\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1e.piscsi_interface.PbDeviceTypeR\x04type\x12H\n" +
	"\x06params\x18\x04 \x03(\v20.piscsi_interface.PbDeviceDefinition.ParamsEntryR\x06params\x12\x1d\n" +
	"\n" +
	"block_size\x18\x05 \x01(\x05R\tblockSize\x12\x16\n" +
	"\x06vendor\x18\x06 \x01(\tR\x06vendor\x12\x18\n" +
	"\aproduct\x18\a \x01(\tR\aproduct\x12\x1a\n" +
	"\brevision\x18\b \x01(\tR\brevision\x12\x1c\n" +
	"\tprotected\x18\t \x01(\bR\tprotected\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x04\n" +
	"\bPbDevice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\x05R\x04unit\x122\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1e.piscsi_interface.PbDeviceTypeR\x04type\x12D\n" +
	"\n" +
	"properties\x18\x04 \x01(\v2$.piscsi_interface.PbDevicePropertiesR\n" +
	"properties\x128\n" +
	"\x06status\x18\x05 \x01(\v2 .piscsi_interface.PbDeviceStatusR\x06status\x121\n" +
	"\x04file\x18\x06 \x01(\v2\x1d.piscsi_interface.PbImageFileR\x04file\x12>\n" +
	"\x06params\x18\a \x03(\v2&.piscsi_interface.PbDevice.ParamsEntryR\x06params\x12\x16\n" +
	"\x06vendor\x18\b \x01(\tR\x06vendor\x12\x18\n" +
	"\aproduct\x18\t \x01(\tR\aproduct\x12\x1a\n" +
	"\brevision\x18\n" +
	" \x01(\tR\brevision\x12\x1d\n" +
	"\n" +
	"block_size\x18\v \x01(\x05R\tblockSize\x12\x1f\n" +
	"\vblock_count\x18\f \x01(\x04R\n" +
	"blockCount\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\rPbDevicesInfo\x124\n" +
	"\adevices\x18\x01 \x03(\v2\x1a.piscsi_interface.PbDeviceR\adevices\"%\n" +
	"\x11PbReservedIdsInfo\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x05R\x03ids\"~\n" +
	"\rPbVersionInfo\x12#\n" +
	"\rmajor_version\x18\x01 \x01(\x05R\fmajorVersion\x12#\n" +
	"\rminor_version\x18\x02 \x01(\x05R\fminorVersion\x12#\n" +
	"\rpatch_version\x18\x03 \x01(\x05R\fpatchVersion\"\x84\x02\n" +
	"\tPbCommand\x12;\n" +
	"\toperation\x18\x01 \x01(\x0e2\x1d.piscsi_interface.PbOperationR\toperation\x12>\n" +
	"\adevices\x18\x02 \x03(\v2$.piscsi_interface.PbDeviceDefinitionR\adevices\x12?\n" +
	"\x06params\x18\x03 \x03(\v2'.piscsi_interface.PbCommand.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\b\n" +
	"\bPbResult\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12<\n" +
	"\n" +
	"error_code\x18\x0e \x01(\x0e2\x1d.piscsi_interface.PbErrorCodeR\terrorCode\x12A\n" +
	"\vserver_info\x18\x03 \x01(\v2\x1e.piscsi_interface.PbServerInfoH\x00R\n" +
	"serverInfo\x12D\n" +
	"\fversion_info\x18\x04 \x01(\v2\x1f.piscsi_interface.PbVersionInfoH\x00R\vversionInfo\x12H\n" +
	"\x0elog_level_info\x18\x05 \x01(\v2 .piscsi_interface.PbLogLevelInfoH\x00R\flogLevelInfo\x12D\n" +
	"\fdevices_info\x18\x06 \x01(\v2\x1f.piscsi_interface.PbDevicesInfoH\x00R\vdevicesInfo\x12Q\n" +
	"\x11device_types_info\x18\a \x01(\v2#.piscsi_interface.PbDeviceTypesInfoH\x00R\x0fdeviceTypesInfo\x12N\n" +
	"\x10image_files_info\x18\b \x01(\v2\".piscsi_interface.PbImageFilesInfoH\x00R\x0eimageFilesInfo\x12G\n" +
	"\x0fimage_file_info\x18\t \x01(\v2\x1d.piscsi_interface.PbImageFileH\x00R\rimageFileInfo\x12c\n" +
	"\x17network_interfaces_info\x18\n" +
	" \x01(\v2).piscsi_interface.PbNetworkInterfacesInfoH\x00R\x15networkInterfacesInfo\x12D\n" +
	"\fmapping_info\x18\v \x01(\v2\x1f.piscsi_interface.PbMappingInfoH\x00R\vmappingInfo\x12Q\n" +
	"\x11reserved_ids_info\x18\f \x01(\v2#.piscsi_interface.PbReservedIdsInfoH\x00R\x0freservedIdsInfo\x12J\n" +
	"\x0eoperation_info\x18\r \x01(\v2!.piscsi_interface.PbOperationInfoH\x00R\roperationInfo\x12M\n" +
	"\x0fstatistics_info\x18\x0f \x01(\v2\".piscsi_interface.PbStatisticsInfoH\x00R\x0estatisticsInfoB\b\n" +
	"\x06result\"\x8c\x06\n" +
	"\fPbServerInfo\x12B\n" +
	"\fversion_info\x18\x01 \x01(\v2\x1f.piscsi_interface.PbVersionInfoR\vversionInfo\x12F\n" +
	"\x0elog_level_info\x18\x02 \x01(\v2 .piscsi_interface.PbLogLevelInfoR\flogLevelInfo\x12O\n" +
	"\x11device_types_info\x18\x03 \x01(\v2#.piscsi_interface.PbDeviceTypesInfoR\x0fdeviceTypesInfo\x12L\n" +
	"\x10image_files_info\x18\x04 \x01(\v2\".piscsi_interface.PbImageFilesInfoR\x0eimageFilesInfo\x12a\n" +
	"\x17network_interfaces_info\x18\x05 \x01(\v2).piscsi_interface.PbNetworkInterfacesInfoR\x15networkInterfacesInfo\x12B\n" +
	"\fmapping_info\x18\x06 \x01(\v2\x1f.piscsi_interface.PbMappingInfoR\vmappingInfo\x12O\n" +
	"\x11reserved_ids_info\x18\a \x01(\v2#.piscsi_interface.PbReservedIdsInfoR\x0freservedIdsInfo\x12B\n" +
	"\fdevices_info\x18\b \x01(\v2\x1f.piscsi_interface.PbDevicesInfoR\vdevicesInfo\x12H\n" +
	"\x0eoperation_info\x18\t \x01(\v2!.piscsi_interface.PbOperationInfoR\roperationInfo\x12K\n" +
	"\x0fstatistics_info\x18\n" +
	" \x01(\v2\".piscsi_interface.PbStatisticsInfoR\x0estatisticsInfo*\x89\x01\n" +
	"\fPbDeviceType\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\f\n" +
	"\x04SAHD\x10\x01\x1a\x02\b\x01\x12\b\n" +
	"\x04SCHD\x10\x02\x12\b\n" +
	"\x04SCRM\x10\x03\x12\b\n" +
	"\x04SCMO\x10\x04\x12\b\n" +
	"\x04SCCD\x10\x05\x12\f\n" +
	"\x04SCBR\x10\x06\x1a\x02\b\x01\x12\b\n" +
	"\x04SCDP\x10\a\x12\b\n" +
	"\x04SCHS\x10\b\x12\b\n" +
	"\x04SCLP\x10\t\x12\b\n" +
	"\x04SCTP\x10\n" +
	"*\xdc\x04\n" +
	"\vPbOperation\x12\x10\n" +
	"\fNO_OPERATION\x10\x00\x12\n" +
	"\n" +
	"\x06ATTACH\x10\x01\x12\n" +
	"\n" +
	"\x06DETACH\x10\x02\x12\x0e\n" +
	"\n" +
	"DETACH_ALL\x10\x03\x12\t\n" +
	"\x05START\x10\x04\x12\b\n" +
	"\x04STOP\x10\x05\x12\n" +
	"\n" +
	"\x06INSERT\x10\x06\x12\t\n" +
	"\x05EJECT\x10\a\x12\v\n" +
	"\aPROTECT\x10\b\x12\r\n" +
	"\tUNPROTECT\x10\t\x12\x0f\n" +
	"\vSERVER_INFO\x10\n" +
	"\x12\x10\n" +
	"\fVERSION_INFO\x10\v\x12\x10\n" +
	"\fDEVICES_INFO\x10\f\x12\x15\n" +
	"\x11DEVICE_TYPES_INFO\x10\r\x12\x1c\n" +
	"\x18DEFAULT_IMAGE_FILES_INFO\x10\x0e\x12\x13\n" +
	"\x0fIMAGE_FILE_INFO\x10\x0f\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x10\x12\x1b\n" +
	"\x17NETWORK_INTERFACES_INFO\x10\x11\x12\x10\n" +
	"\fMAPPING_INFO\x10\x12\x12\x15\n" +
	"\x11RESERVED_IDS_INFO\x10\x13\x12\x12\n" +
	"\x0eDEFAULT_FOLDER\x10\x14\x12\r\n" +
	"\tLOG_LEVEL\x10\x15\x12\x0f\n" +
	"\vRESERVE_IDS\x10\x16\x12\r\n" +
	"\tSHUT_DOWN\x10\x17\x12\x10\n" +
	"\fCREATE_IMAGE\x10\x18\x12\x10\n" +
	"\fDELETE_IMAGE\x10\x19\x12\x10\n" +
	"\fRENAME_IMAGE\x10\x1a\x12\x0e\n" +
	"\n" +
	"COPY_IMAGE\x10\x1b\x12\x11\n" +
	"\rPROTECT_IMAGE\x10\x1c\x12\x13\n" +
	"\x0fUNPROTECT_IMAGE\x10\x1d\x12\x18\n" +
	"\x14CHECK_AUTHENTICATION\x10\x1e\x12\x12\n" +
	"\x0eOPERATION_INFO\x10\x1f\x12\x13\n" +
	"\x0fSTATISTICS_INFO\x10 *I\n" +
	"\vPbErrorCode\x12\x11\n" +
	"\rNO_ERROR_CODE\x10\x00\x12\x15\n" +
	"\x11UNKNOWN_OPERATION\x10\x01\x12\x10\n" +
	"\fUNAUTHORIZED\x10\x02*f\n" +
	"\x14PbStatisticsCategory\x12\x11\n" +
	"\rCATEGORY_NONE\x10\x00\x12\x11\n" +
	"\rCATEGORY_INFO\x10\x01\x12\x14\n" +
	"\x10CATEGORY_WARNING\x10\x02\x12\x12\n" +
	"\x0eCATEGORY_ERROR\x10\x03b\x06proto3"

var (
	file_piscsi_interface_proto_rawDescOnce sync.Once
	file_piscsi_interface_proto_rawDescData []byte
)

func file_piscsi_interface_proto_rawDescGZIP() []byte {
	file_piscsi_interface_proto_rawDescOnce.Do(func() {
		file_piscsi_interface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_piscsi_interface_proto_rawDesc), len(file_piscsi_interface_proto_rawDesc)))
	})
	return file_piscsi_interface_proto_rawDescData
}

var file_piscsi_interface_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_piscsi_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_piscsi_interface_proto_goTypes = []any{
	(PbDeviceType)(0),               // 0: piscsi_interface.PbDeviceType
	(PbOperation)(0),                // 1: piscsi_interface.PbOperation
	(PbErrorCode)(0),                // 2: piscsi_interface.PbErrorCode
	(PbStatisticsCategory)(0),       // 3: piscsi_interface.PbStatisticsCategory
	(*PbOperationParameter)(nil),    // 4: piscsi_interface.PbOperationParameter
	(*PbOperationMetaData)(nil),     // 5: piscsi_interface.PbOperationMetaData
	(*PbOperationInfo)(nil),         // 6: piscsi_interface.PbOperationInfo
	(*PbMappingInfo)(nil),           // 7: piscsi_interface.PbMappingInfo
	(*PbDeviceProperties)(nil),      // 8: piscsi_interface.PbDeviceProperties
	(*PbDeviceStatus)(nil),          // 9: piscsi_interface.PbDeviceStatus
	(*PbDeviceTypeProperties)(nil),  // 10: piscsi_interface.PbDeviceTypeProperties
	(*PbDeviceTypesInfo)(nil),       // 11: piscsi_interface.PbDeviceTypesInfo
	(*PbImageFile)(nil),             // 12: piscsi_interface.PbImageFile
	(*PbImageFilesInfo)(nil),        // 13: piscsi_interface.PbImageFilesInfo
	(*PbLogLevelInfo)(nil),          // 14: piscsi_interface.PbLogLevelInfo
	(*PbNetworkInterfacesInfo)(nil), // 15: piscsi_interface.PbNetworkInterfacesInfo
	(*PbStatistics)(nil),            // 16: piscsi_interface.PbStatistics
	(*PbStatisticsInfo)(nil),        // 17: piscsi_interface.PbStatisticsInfo
	(*PbDeviceDefinition)(nil),      // 18: piscsi_interface.PbDeviceDefinition
	(*PbDevice)(nil),                // 19: piscsi_interface.PbDevice
	(*PbDevicesInfo)(nil),           // 20: piscsi_interface.PbDevicesInfo
	(*PbReservedIdsInfo)(nil),       // 21: piscsi_interface.PbReservedIdsInfo
	(*PbVersionInfo)(nil),           // 22: piscsi_interface.PbVersionInfo
	(*PbCommand)(nil),               // 23: piscsi_interface.PbCommand
	(*PbResult)(nil),                // 24: piscsi_interface.PbResult
	(*PbServerInfo)(nil),            // 25: piscsi_interface.PbServerInfo
	nil,                             // 26: piscsi_interface.PbOperationInfo.OperationsEntry
	nil,                             // 27: piscsi_interface.PbMappingInfo.MappingEntry
	nil,                             // 28: piscsi_interface.PbDeviceProperties.DefaultParamsEntry
	nil,                             // 29: piscsi_interface.PbDeviceDefinition.ParamsEntry
	nil,                             // 30: piscsi_interface.PbDevice.ParamsEntry
	nil,                             // 31: piscsi_interface.PbCommand.ParamsEntry
}
var file_piscsi_interface_proto_depIdxs = []int32{
	4,  // 0: piscsi_interface.PbOperationMetaData.parameters:type_name -> piscsi_interface.PbOperationParameter
	26, // 1: piscsi_interface.PbOperationInfo.operations:type_name -> piscsi_interface.PbOperationInfo.OperationsEntry
	27, // 2: piscsi_interface.PbMappingInfo.mapping:type_name -> piscsi_interface.PbMappingInfo.MappingEntry
	28, // 3: piscsi_interface.PbDeviceProperties.default_params:type_name -> piscsi_interface.PbDeviceProperties.DefaultParamsEntry
	0,  // 4: piscsi_interface.PbDeviceTypeProperties.type:type_name -> piscsi_interface.PbDeviceType
	8,  // 5: piscsi_interface.PbDeviceTypeProperties.properties:type_name -> piscsi_interface.PbDeviceProperties
	10, // 6: piscsi_interface.PbDeviceTypesInfo.properties:type_name -> piscsi_interface.PbDeviceTypeProperties
	0,  // 7: piscsi_interface.PbImageFile.type:type_name -> piscsi_interface.PbDeviceType
	12, // 8: piscsi_interface.PbImageFilesInfo.image_files:type_name -> piscsi_interface.PbImageFile
	3,  // 9: piscsi_interface.PbStatistics.category:type_name -> piscsi_interface.PbStatisticsCategory
	16, // 10: piscsi_interface.PbStatisticsInfo.statistics:type_name -> piscsi_interface.PbStatistics
	0,  // 11: piscsi_interface.PbDeviceDefinition.type:type_name -> piscsi_interface.PbDeviceType
	29, // 12: piscsi_interface.PbDeviceDefinition.params:type_name -> piscsi_interface.PbDeviceDefinition.ParamsEntry
	0,  // 13: piscsi_interface.PbDevice.type:type_name -> piscsi_interface.PbDeviceType
	8,  // 14: piscsi_interface.PbDevice.properties:type_name -> piscsi_interface.PbDeviceProperties
	9,  // 15: piscsi_interface.PbDevice.status:type_name -> piscsi_interface.PbDeviceStatus
	12, // 16: piscsi_interface.PbDevice.file:type_name -> piscsi_interface.PbImageFile
	30, // 17: piscsi_interface.PbDevice.params:type_name -> piscsi_interface.PbDevice.ParamsEntry
	19, // 18: piscsi_interface.PbDevicesInfo.devices:type_name -> piscsi_interface.PbDevice
	1,  // 19: piscsi_interface.PbCommand.operation:type_name -> piscsi_interface.PbOperation
	18, // 20: piscsi_interface.PbCommand.devices:type_name -> piscsi_interface.PbDeviceDefinition
	31, // 21: piscsi_interface.PbCommand.params:type_name -> piscsi_interface.PbCommand.ParamsEntry
	2,  // 22: piscsi_interface.PbResult.error_code:type_name -> piscsi_interface.PbErrorCode
	25, // 23: piscsi_interface.PbResult.server_info:type_name -> piscsi_interface.PbServerInfo
	22, // 24: piscsi_interface.PbResult.version_info:type_name -> piscsi_interface.PbVersionInfo
	14, // 25: piscsi_interface.PbResult.log_level_info:type_name -> piscsi_interface.PbLogLevelInfo
	20, // 26: piscsi_interface.PbResult.devices_info:type_name -> piscsi_interface.PbDevicesInfo
	11, // 27: piscsi_interface.PbResult.device_types_info:type_name -> piscsi_interface.PbDeviceTypesInfo
	13, // 28: piscsi_interface.PbResult.image_files_info:type_name -> piscsi_interface.PbImageFilesInfo
	12, // 29: piscsi_interface.PbResult.image_file_info:type_name -> piscsi_interface.PbImageFile
	15, // 30: piscsi_interface.PbResult.network_interfaces_info:type_name -> piscsi_interface.PbNetworkInterfacesInfo
	7,  // 31: piscsi_interface.PbResult.mapping_info:type_name -> piscsi_interface.PbMappingInfo
	21, // 32: piscsi_interface.PbResult.reserved_ids_info:type_name -> piscsi_interface.PbReservedIdsInfo
	6,  // 33: piscsi_interface.PbResult.operation_info:type_name -> piscsi_interface.PbOperationInfo
	17, // 34: piscsi_interface.PbResult.statistics_info:type_name -> piscsi_interface.PbStatisticsInfo
	22, // 35: piscsi_interface.PbServerInfo.version_info:type_name -> piscsi_interface.PbVersionInfo
	14, // 36: piscsi_interface.PbServerInfo.log_level_info:type_name -> piscsi_interface.PbLogLevelInfo
	11, // 37: piscsi_interface.PbServerInfo.device_types_info:type_name -> piscsi_interface.PbDeviceTypesInfo
	13, // 38: piscsi_interface.PbServerInfo.image_files_info:type_name -> piscsi_interface.PbImageFilesInfo
	15, // 39: piscsi_interface.PbServerInfo.network_interfaces_info:type_name -> piscsi_interface.PbNetworkInterfacesInfo
	7,  // 40: piscsi_interface.PbServerInfo.mapping_info:type_name -> piscsi_interface.PbMappingInfo
	21, // 41: piscsi_interface.PbServerInfo.reserved_ids_info:type_name -> piscsi_interface.PbReservedIdsInfo
	20, // 42: piscsi_interface.PbServerInfo.devices_info:type_name -> piscsi_interface.PbDevicesInfo
	6,  // 43: piscsi_interface.PbServerInfo.operation_info:type_name -> piscsi_interface.PbOperationInfo
	17, // 44: piscsi_interface.PbServerInfo.statistics_info:type_name -> piscsi_interface.PbStatisticsInfo
	5,  // 45: piscsi_interface.PbOperationInfo.OperationsEntry.value:type_name -> piscsi_interface.PbOperationMetaData
	0,  // 46: piscsi_interface.PbMappingInfo.MappingEntry.value:type_name -> piscsi_interface.PbDeviceType
	47, // [47:47] is the sub-list for method output_type
	47, // [47:47] is the sub-list for method input_type
	47, // [47:47] is the sub-list for extension type_name
	47, // [47:47] is the sub-list for extension extendee
	0,  // [0:47] is the sub-list for field type_name
}

func init() { file_piscsi_interface_proto_init() }
func file_piscsi_interface_proto_init() {
	if File_piscsi_interface_proto != nil {
		return
	}
	file_piscsi_interface_proto_msgTypes[20].OneofWrappers = []any{
		(*PbResult_ServerInfo)(nil),
		(*PbResult_VersionInfo)(nil),
		(*PbResult_LogLevelInfo)(nil),
		(*PbResult_DevicesInfo)(nil),
		(*PbResult_DeviceTypesInfo)(nil),
		(*PbResult_ImageFilesInfo)(nil),
		(*PbResult_ImageFileInfo)(nil),
		(*PbResult_NetworkInterfacesInfo)(nil),
		(*PbResult_MappingInfo)(nil),
		(*PbResult_ReservedIdsInfo)(nil),
		(*PbResult_OperationInfo)(nil),
		(*PbResult_StatisticsInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_piscsi_interface_proto_rawDesc), len(file_piscsi_interface_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_piscsi_interface_proto_goTypes,
		DependencyIndexes: file_piscsi_interface_proto_depIdxs,
		EnumInfos:         file_piscsi_interface_proto_enumTypes,
		MessageInfos:      file_piscsi_interface_proto_msgTypes,
	}.Build()
	File_piscsi_interface_proto = out.File
	file_piscsi_interface_proto_goTypes = nil
	file_piscsi_interface_proto_depIdxs = nil
}
